### ISSUE TITLE
Test_aln function doesn't quite work

### ISSUE THREAD

**Issue by roblanf** [Wen-Zha/Matched-Pairs-Test-of-Homogeneity#8]
In this function, you call 'dat.charsets()', but there is no ```dat``` in the function anywhere. 

Be careful about what you are passing to the function, and what are are not.

The cleanest thing to do here is to split this so that you have:

(i) A function that deals with a charset
(ii) An outer function that deals with the alignment

**Comment by roblanf** [comment]
ah but I also see in your code that you are (sensibly) having the outer loop iterate over all pairs of taxa. 

You should probably stick to this. But at the same time you need to fix up that function so that it doesn't try to use things that aren't there like `dat`

**Comment by Wen-Zha** [comment]
Not sure which the first revision this was fixed in, but  Test_aln should stand alone from https://github.com/istigatrice/Matched-Pairs-Test-of-Homogeneity/commit/5563fd7b04f975312346de32d567176dcf253cd8 onwards
