### ISSUE TITLE
dynamically adding to an array

### ISSUE THREAD

**Issue by roblanf** [Wen-Zha/Matched-Pairs-Test-of-Homogeneity#9]
Your code is a little slower than it could be right now. A key issue is that you are adding to the array `p` one row at a time. This is slow, because memory keeps having to be reallocated. The bigger the array gets, the slower it gets to add to it. (So the problem will be really bad on really large datasets).

Better would be to figure out ahead of time how big `p` needs to be, make an array that size, and then fill it in as you go. This will be much much faster. 

Perhaps even better than that is to just write out the lines of p to a csv file as you go - you don't actually need to store it in memory at all.

**Comment by roblanf** [comment]
Hints: use numpy.savetxt() and look here: http://stackoverflow.com/questions/27786868/python3-numpy-appending-to-a-file-using-numpy-savetxt

**Comment by Wen-Zha** [comment]
Have taken the approach of figuring out ahead of time how big p needs to be. See: https://github.com/istigatrice/Matched-Pairs-Test-of-Homogeneity/commit/5563fd7b04f975312346de32d567176dcf253cd8

**Comment by roblanf** [comment]
Cool. once it's fixed you can close the issue with the 'close and comment' button below. You can still see it later if you need to (or even re-open it).
